### ISSUE TITLE
Some doubts about dataset VQA-RAD

### ISSUE THREAD

**Issue by Feng-Sir0** [GaryGuTC/LaPA_model#2]
Hi, That's a good jod!
I am very interested in your work. But I have two questions about the details:
(1)  How many Total Answers are there in the training process of the model on the VQA-RAD dataset?
(2) When predicting answers, the VQA task is seen as a multi-class task. So how many categories (or candidate answers)?

**Comment by GaryGuTC** [comment]
Hi

Thanks so much for your questions.

VQA-RAD total categories and answers: vqa_label_size = 498, Please refer [here](https://github.com/GaryGuTC/LaPA_model/blob/963e0523f623a32a32e20112bbd291569465fcbb/m3ae/config.py#L159).

Best regards

**Comment by Feng-Sir0** [comment]
Thanks！😊
