### ISSUE TITLE
problem with test result

### ISSUE THREAD

**Issue by YAO-EE** [GaryGuTC/LaPA_model#7]
Dear author, thank you for contributing such interesting work!!!
I preprocessed the vqa_rad dataset and slake dataset according to the steps provided by the author, downloaded the corresponding files and weights, and the result is as follows:
![image](https://github.com/user-attachments/assets/10d11b1e-2437-4816-b378-b7679eaacb87)
This result is inconsistent with the original text, is there any step I am missing?
----------------------------------------------------------------------------------------------
preprocess dataset
![image](https://github.com/user-attachments/assets/f693dd96-681a-49f0-aee5-b225860430ce)
----------------------------------------------------------------------------------------------
+download
![image](https://github.com/user-attachments/assets/c225608c-3801-4ecb-9152-a5f11260a427)

**Comment by GaryGuTC** [comment]
Hi,
Thank you very much for your attention to our work.
Please double-check the following:
1. Each step in the README.
2. The dataset download.
3. The library versions in the environment. (Important!)

During my experiments, the results showed some fluctuations (very small), which is normal. 

Best regards

**Comment by YAO-EE** [comment]
Thanks for your reply!
I installed the library according to the environment you provided and the problem was solved!!!
